/* Original TechFlow Lottie artwork. Run: node scripts/build-orbit.cjs */
const fs = require('node:fs');
const path = require('node:path');
const dir = path.join(__dirname, '..', 'animations');
const prop = k => ({ a: 0, k });
const key = (from, to, end = 360) => ({ a: 1, k: [
    { t: 0, s: [from], e: [to], o: { x: [0], y: [0] }, i: { x: [1], y: [1] } },
    { t: end, s: [to] },
] });
const transform = (rotation = prop(0)) => ({ ty: 'tr', p: prop([0,0]), a: prop([0,0]), s: prop([100,100]), r: rotation, o: prop(100), sk: prop(0), sa: prop(0) });
const layers = [];
function layer(name, shapes, rotation = prop(0), opacity = 100) {
    layers.push({ ddd: 0, ind: layers.length + 1, ty: 4, nm: name, sr: 1, ks: { o: prop(opacity), r: rotation, p: prop([300,300,0]), a: prop([0,0,0]), s: prop([100,100,100]) }, ao: 0, shapes, ip: 0, op: 360, st: 0, bm: 0 });
}
function ellipse(size, color, width, opacity = 100, position = [0,0]) {
    return [{ ty: 'el', d: 1, s: prop(size), p: prop(position), nm: 'Orbit contour' }, { ty: 'st', c: prop(color), o: prop(opacity), w: prop(width), lc: 2, lj: 2, ml: 4 }];
}
// Slowly rotating meridians create the depth of a luminous, woven sphere.
for (let i = 0; i < 22; i++) {
    const angle = i * 180 / 22;
    const color = [.66 + i * .007, .71 + i * .005, .63 + i * .006, 1];
    const shapes = [{ ty: 'gr', nm: `Meridian ${i + 1}`, it: [...ellipse([112 + Math.sin(i / 22 * Math.PI) * 110, 340], color, 1.5, 80), transform(key(angle, angle + 180))] }];
    layer(`Silk meridian ${i + 1}`, shapes, prop(-28));
}
// Elliptical paths and orbiting satellites share the same rotated plane.
for (let i = 0; i < 3; i++) {
    const angle = i * 60 + 15;
    layer(`Outer orbit ${i}`, [{ ty: 'gr', it: [...ellipse([440, 220], [.74,.58,.40,1], .8, 35), transform(prop(angle))] }]);
    const frames = [];
    for (let n = 0; n <= 72; n++) {
        const a = n / 72 * Math.PI * 2 + i * 2;
        const x = Math.cos(a) * 220, y = Math.sin(a) * 110, r = angle * Math.PI / 180;
        frames.push({ t: n * 5, s: [x * Math.cos(r) - y * Math.sin(r), x * Math.sin(r) + y * Math.cos(r)], o: {x:.33,y:.33}, i: {x:.67,y:.67} });
    }
    layer(`Satellite ${i}`, [{ty:'el',d:1,s:prop([8,8]),p:{a:1,k:frames}}, {ty:'fl',c:prop([.96,.94,.86,1]),o:prop(100),r:1}]);
}
layer('Quiet central light', [
    {ty:'gr',it:[...ellipse([56,56],[.83,.88,.78,1],1,55),transform()]},
    {ty:'gr',it:[{ty:'el',d:1,s:prop([10,10]),p:prop([0,0])},{ty:'fl',c:prop([.8,1,.94,1]),o:prop(90),r:1},transform()]},
]);
const animation = { v: '5.12.2', fr: 60, ip: 0, op: 360, w: 600, h: 600, nm: 'TechFlow — Orbital intelligence', ddd: 0, assets: [], layers, markers: [] };
fs.mkdirSync(dir, {recursive:true});
fs.writeFileSync(path.join(dir, 'flow-orbit.json'), JSON.stringify(animation));
fs.writeFileSync(path.join(dir, 'flow-orbit.js'), '/* Generated by scripts/build-orbit.cjs. Original TechFlow artwork. */\nwindow.TechFlowOrbit = ' + JSON.stringify(animation) + ';\n');
console.log(`Built Lottie artwork: ${layers.length} layers, ${animation.op / animation.fr}s seamless loop.`);
